curl -O http://www.nextel.com.mx/promociones/promo-blackberry9620.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-bright.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-contact.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-clip.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-link.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-polaris.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-stella.html
curl -O http://www.nextel.com.mx/promociones/promo-huawei-stick.html
curl -O http://www.nextel.com.mx/promociones/promo-motorola-master.html
curl -O http://www.nextel.com.mx/promociones/promo-motorola-master-touch.html
curl -O http://www.nextel.com.mx/promociones/promo-ferrari-xt621-edicion-especial.html
curl -O http://www.nextel.com.mx/promociones/promo-ferrari-xt621-limited-edition.html