#curl -O http://www.nextel.com.mx/promociones/promo-alcatel-onetouch-mpop-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-blu-dash.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-bright.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-contact.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-clip.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-link.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-mate7.html
#curl -O http://www.nextel.com.mx/promociones/promo-huawei-rugged.html
#curl -O http://www.nextel.com.mx/promociones/promo-moto-e-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-moto-g-ferrari-edition-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-moto-g-2da-generacion-conexion.html
#curl -O http://www.nextel.com.mx/promociones/promo-motorola-x-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-moto-x-2da-generacion.html
#curl -O http://www.nextel.com.mx/promociones/promo-motorola-nexus6.html
#curl -O http://www.nextel.com.mx/promociones/promo-samsung-galaxy-core-plus-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-samsung-galaxy-s5-prip-plan.html
#curl -O http://www.nextel.com.mx/promociones/promo-v35-conexion.html
#curl -O http://www.nextel.com.mx/promociones/promo-v45-prip-plan.html
wget -N http://www.nextel.com.mx/equipos/blu-dash.html
wget -N http://www.nextel.com.mx/equipos/blu-dash-c-music.html
wget -N http://www.nextel.com.mx/equipos/huawei-g7.html
wget -N http://www.nextel.com.mx/equipos/huawei-mate7.html
wget -N http://www.nextel.com.mx/equipos/huawei-y520.html
wget -N http://www.nextel.com.mx/equipos/moto-e.html
wget -N http://www.nextel.com.mx/equipos/moto-g-ferrari-edition.html
wget -N http://www.nextel.com.mx/equipos/moto-g-2da-generacion.html
wget -N http://www.nextel.com.mx/equipos/moto-x-2da-generacion.html
wget -N http://www.nextel.com.mx/equipos/motorola-nexus6.html
wget -N http://www.nextel.com.mx/equipos/samsung-galaxy-core-plus.html
wget -N http://www.nextel.com.mx/equipos/samsung-galaxy-e5.html
wget -N http://www.nextel.com.mx/equipos/samsung-galaxy-e7.html
wget -N http://www.nextel.com.mx/equipos/galaxy-s5-equipo.html
wget -N http://www.nextel.com.mx/equipos/samsung-galaxy-s6.html
wget -N http://www.nextel.com.mx/equipos/samsung-galaxy-s6-edge.html
wget -N http://www.nextel.com.mx/equipos/equipo-v35.html
wget -N http://www.nextel.com.mx/equipos/equipo-v45.html

